name: Run Weibo Script

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
        
    - name: Install wget
      run: pip install wget==3.2
      
    - name: Install requests-html
      run: pip install requests-html==0.10.0
      
    - name: Install BeautifulSoup
      run: pip install beautifulsoup4==4.8.2
      
    - name: Run Python Script
      run: python weibo.py
