name: run_weibo

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  Telegram_Bot_Token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
  Telegram_Chat_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
  Weibo_ID: ${{ secrets.WEIBO_ID }}
  Proxy: ${{ secrets.PROXY }}

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.head.sha }}
        
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9' # 你想要使用的 Python 版本
        
    - name: Install Dependencies
      run: |
        pip install -r requirements.txt
        pip install lxml_html_clean

    - name: Run Python Script
      run: python weibo.py
