name: Workflow1

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  my_job:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        run: echo "This is step 1"
      - name: Step 2 (Uses Secret)
        env:
          WEIBO_ID: ${{ secrets.WEIBO_ID }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      # Add more steps if needed
  trigger_next_workflow:
    runs-on: ubuntu-latest
    needs: my_job
    steps:
      - name: Trigger Workflow2
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { data: workflows } = await github.actions.listRepoWorkflows({
              owner: context.repo.owner,
              repo: context.repo.repo
            });
            const workflow = workflows.find(w => w.name === 'Workflow2');
            await github.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: workflow.id,
              ref: 'main' // Trigger on main branch
            });
